POST http://localhost:8080/api/user/token
Content-Type: application/json

{
  "username": "root",
  "password": "b867e4d87037b340c1490f78b05d9d1d102adf164223a571d5cd8027afaff1ce"
}

> {%
    client.global.set("my_cookie", response.headers.valuesOf("Set-Cookie")[0]);
    console.log(client.global.get("my_cookie"))
%}

###


GET http://localhost:8080/api/statistic/billCountByState
Cookie: {{my_cookie}}

###

PUT http://localhost:8080/api/serviceBill/processed
Content-Type: application/json
Cookie: {{my_cookie}}

{
  "ids": [
    1224
  ],
  "processedDate": "2024-08-12T16:00:00.000Z"
}