POST http://localhost:8080/api/user/token
Content-Type: application/json

{
  "username": "root",
  "password": "admin"
}

> {%
    const token = response.headers.valueOf('x-auth-token')
    client.global.set("authorization", "Bearer " + token)
%}


###


GET http://localhost:8080/api/statistic/billCountByState
Authorization: {{authorization}}


###

PUT http://localhost:8080/api/serviceBill/processed
Authorization: {{authorization}}
Content-Type: application/json

{
  "ids": [
    1224
  ],
  "processedDate": "2024-08-12T16:00:00.000Z"
}