services:
  postgres:
    image: postgres:18-alpine
    container_name: eac-postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      start_period: 5s
#  ocr-server:
#    build:
#      context: ./ocr-server
#    image: ocr-server:latest
#    ports:
#      - "9003:9003"
  backend:
    image: alpine:3
    container_name: eac-backend-go
    depends_on:
      postgres:
        condition: service_healthy
#      - ocr-server
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
#      - OCR_URL=http://ocr-server:9003
    env_file:
      - .env
    volumes:
      - ./backend-go:/app/backend
    command: sh -c "cd /app/backend/ && ./backend-go"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8080 || exit 1"]
      start_period: 5s
  frontend:
    image: caddy:2-alpine
    container_name: eac-frontend
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://backend:8080
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/conf/Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/cert:/data/caddy
      - ./frontend/html:/usr/share/caddy:ro
volumes:
  pgdata: