services:
  postgres:
    image: postgres:18-alpine
    container_name: eac-postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      start_period: 5s
  backend:
    image: eclipse-temurin:25-jre-alpine
    container_name: eac-backend-java
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    env_file:
      - .env
    volumes:
      - ./backend-java:/app/backend
    command: sh -c "cd /app/backend && java -jar app.jar"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8080 || exit 1"]
      start_period: 5s
  frontend:
    image: caddy:2-alpine
    container_name: eac-frontend
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://backend:8080
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/conf/Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/cert:/data/caddy
      - ./frontend/html:/usr/share/caddy:ro
volumes:
  pgdata: